import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Hadia Khan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
