"use client";
import Head from "next/head";
import { AiFillGithub, AiFillMail, AiFillLinkedin } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Link from 'next/link'
import Image from 'next/image';
import profileImage from './assets/IMG_7372.jpg';
import fullstack from './assets/fullstack.png';
import scale from './assets/scale.png';
import robust from './assets/robust.png';
import web1 from './assets/web1.png';
import web2 from './assets/web2.png';
import web3 from './assets/web3.png';
import web4 from './assets/web4.png';
import web5 from './assets/web5.png';
import web6 from './assets/web6.png';
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Hadia Khan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">developedbyhadia</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl dark:fill-white" onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li>
                <Link className="bg-gradient-to-r from-cyan-400 to-cyan-700 py-4 px-2 text-white rounded-md ml-8"
                  href="/resume.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                //  download="Hadia_Khan_Resume.pdf"
                >
                  Resume
                </Link>
              </li>

              {/* <li><a href="#about">About</a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#contact">Contact</a></li> */}
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-cyan-500 font-semibold md:text-6xl tracking-tight"> Hadia Khan </h2>
            <h3 className="text-xl font-sans font-medium py-2 md:text-2xl tracking-wide dark:text-white">Developer and Engineer.</h3>
            <p className="font-sans text-md py-5 leading-8 text-gray-600 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              Full Stack Developer by title, professional problem solver by nature—React, TypeScript, Node.js, and a touch of caffeine to fuel my magic.
              {/* Full Stack developer, with proficiency in multiple stacks including React, Next, Node, Django, and beyond.
                At my core, I'm a problem solver—ready to tackle any challenge that comes my way! */}
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500">
            {/* <AiFillTwitterCircle /> */}
            {/* <AiFillGoogleCircle /> */}
            <a href="https://www.linkedin.com/in/hadia-khan-7b11861a5/" target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/HadiaK99" target="_blank" rel="noopener noreferrer">
              <AiFillGithub />
            </a>
            <a href="mailto:hadiak54321@gmail.com" target="_blank" rel="noopener noreferrer">
              <AiFillMail />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-cyan-500 rounded-full w-80 h-80 mt-20 overflow-hidden  md:w-96 md:h-96">
            <Image src={profileImage} alt="Hadia Khan" layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl font-semibold py-1 dark:text-cyan-400">Services I offer</h3>
            <p className="font-sans text-md py-2 leading-8 text-gray-600 dark:text-gray-400">
              Code whisperer by day, bug wrangler by night.
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-700 dark:text-white">
              Creating seamless <span className="text-cyan-500">user experiences</span>, powerful <span className="text-cyan-500">back-end solutions</span>, and everything in between—customized to bring your ideas to life.
            </p> */}
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center justify-items-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="fullstack" src={fullstack} width={100} height={100} />
              <h3 className="text-lg font-semibold pt-8 pb-2 tracking-tight dark:text-gray-300">Full-Stack Development</h3>
              <p className="font-sans py-2 dark:text-gray-200">Turning ideas into production-ready applications with modern frontend, backend, and cloud technologies—built to be fast, reliable, and actually enjoyable to use.</p>
              <h4 className="py-4 font-semibold text-cyan-600">Technologies I Use</h4>
              <p className="text-gray-700 py-1 dark:text-gray-400">React, Next.js, TypeScript</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">Node.js, Express, Python</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">GraphQL, REST APIs</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">SQL, PostgreSQL, Neo4j</p>
            </div>
            <div className="text-center justify-items-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="robust" src={robust} width={100} height={100} />
              <h3 className="text-lg font-bold pt-8 pb-2 tracking-tight dark:text-gray-300">Clean & Maintainable Code</h3>
              <p className="font-sans py-2 dark:text-gray-200">Writing code that future-me won't have to fight with. I focus on modular architecture, reusable components, efficient APIs, and code that's built to evolve as the product grows.</p>
              <h4 className="py-4 font-bold text-cyan-600">Languages and Frameworks I Use</h4>
              <p className="text-gray-700 py-1 dark:text-gray-400">JavaScript (ES6+), TypeScript</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">Python, SQL</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">Redux Saga</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">Git, GitHub</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">Docker, Redis</p>
            </div>
            <div className="text-center justify-items-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="scale" src={scale} width={100} height={100} />
              <h3 className="text-lg font-semibold pt-8 pb-2 tracking-tight dark:text-gray-300">Scalable System Architecture</h3>
              <p className="font-sans py-2 dark:text-gray-200">Designing systems that don't fall apart when the user count goes up. From serverless backends to authentication, payments, and third-party integrations, I build the pieces that keep applications running smoothly.</p>
              <h4 className="py-4 font-semibold text-cyan-600">Technologies & Services</h4>
              <p className="text-gray-700 py-1 dark:text-gray-400">Google & Microsoft SSO</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">Stripe Payment Integration</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">GraphQL APIs & Optimized Queries</p>
              <p className="text-gray-700 py-1 dark:text-gray-400">Automated Workflows</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl font-semibold py-1 dark:text-cyan-400">Portfolio</h3>
            {/* <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-400">
              Code whisperer by day, bug wrangler by night.
            </p> */}
            <p className="font-sans text-md py-2 leading-8 text-gray-600 dark:text-gray-300">
              A collection of things I've <span className="text-cyan-500">built</span>, <span className="text-cyan-600">broken</span>, <span className="text-cyan-700">fixed</span>, and somehow made work—thoughtfully crafted from pixels to production.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image alt="web1" src={web1} className="rounded-lg object-cover" height={'100%'} width={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image alt="web2" src={web2} className="rounded-lg object-cover" height={'100%'} width={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image alt="web6" src={web6} className="rounded-lg object-cover" height={'100%'} width={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image alt="web4" src={web4} className="rounded-lg object-cover" height={'100%'} width={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image alt="web5" src={web5} className="rounded-lg object-cover" height={'100%'} width={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image alt="web3" src={web3} className="rounded-lg object-cover" height={'100%'} width={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
